# numpy basics - for mathematical operations

In [43]:
import numpy as np 

In [44]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [45]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(type(b))
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
<class 'numpy.ndarray'>
(5, 1)


In [46]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(type(c))
print(c.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [47]:
#create arrays of zeros, ones and custom array

d = np.zeros((3,3))
print(d)

e = np.ones((2,3))
print(e)

#array of constants

a = np.full((3,2),5)
print(a)

#identity matrix - size/square matrix
b = np.eye(4)
print(b)

#random matrix

randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.6583112  0.20113234 0.43278918]
 [0.53021455 0.8643974  0.39760658]]


In [48]:
print(randomMatrix[:,1])

[0.20113234 0.8643974 ]


In [49]:
randomMatrix[1,1:] = 1
print(randomMatrix)

[[0.6583112  0.20113234 0.43278918]
 [0.53021455 1.         1.        ]]


In [50]:
z = np.zeros((3,3), dtype = np.int64)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [51]:
#datatype
print(z.dtype)

int64


In [52]:
#Mathematical operations

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x)
print(y)

print(x+y)
print(np.add(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [53]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [54]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [55]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [56]:
#multiply/dot product

print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [71]:
#MULTIPLY (DOT PRODUCT) OF VECTORS => SCALERS

a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

print(a.dot(b))
print(np.dot(a,b))

30
30


In [72]:
print(a)

[1 2 3 4]


In [73]:
print(sum(a))

10


In [74]:
print(np.sum(x))

10


In [75]:
#stacking of arrays

print(a)
b = b+2
print(b)

[1 2 3 4]
[3 4 5 6]


In [77]:
np.stack((a,b),axis = 1) #0 - row axis
#1 - coloumn axis

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

In [68]:
#reshaping the array

a = a.reshape((4,-1))
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


# NUMPY RANDOM MODULE

--->rand: Random values in a given shape.
--->randn: Return a sample (or samples) from the "standard normal " distribution.
--->randint: Return random integers from low (inclusive) to high (exclusive).
---> random: Return random floats in the half-open interval [0.0,1.0)
---> choice: Generates a random sample from a given !-D array
--> Shuffle: Shuffles the contents of a sequence


In [78]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [79]:
a = np.arange(10) +5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [80]:
np.random.shuffle(a)
print(a)

[13  5  9 10  6 12 11 14  8  7]


In [86]:
a = np.random.rand(2,3)
print(a)

[[0.14091958 0.78181879 0.97819417]
 [0.00403391 0.57184559 0.85364708]]


In [88]:
a = np.random.randn(2,3)
print(a)

[[ 0.38716645  1.20527835 -1.18116214]
 [ 0.07702932  1.5932975  -0.12724535]]


In [92]:
a = np.random.randint(5,10,5)
print(a)

#pick the random number
element = np.random.choice([11,2,4,56,78])
print(element)

[8 7 7 6 6]
2


# Some more numpy functions  - STATISTICS

-->min
-->mean
-->median
-->average
-->variance
-->standard deviation




In [97]:
a = np.array([[1,2,3,4,5],[6,7,8,9,1]])
print(a)
print(np.min(a))
print(np.min(a,axis=0)) #rows changes column remains same
print(np.min(a,axis=1))

[[1 2 3 4 5]
 [6 7 8 9 1]]
1
[1 2 3 4 1]
[1 1]


In [98]:
#median

b = np.array([1,2,3,4,5])
print(np.median(b))

3.0


In [101]:
#mean vs average is weighted

c = np.array([1,5,2,3,0])
print(np.mean(c))

w = np.array([1,2,3,4,5])
print(np.average(c,weights = w))

2.2
1.9333333333333333


In [103]:
#standard deviation

u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

print(np.std(c))

#variance

print(myStd**2)
print(np.var(c))

1.7204650534085253
1.7204650534085253
2.96
2.96
